### ISSUE TITLE
The Confidence Interval of the Robust Conformal Inference

### ISSUE THREAD

**Issue by mxu1219** [kwuthrich/scinference#3]
Thank you for writing down the codes of the paper "An Exact and Robust Conformal Inference Method for Counterfactual and Synthetic Controls". I have a question in practice. 
I apply this inference method to several cases. In some cases, I find that the confidence interval looks quite weird. For example, there is one case that 
1. the estimated difference from T0+1 to T0+T1 is: -23135.52 -245464.06 -250619.72 -270884.35  -16402.96 -322834.17 -467124.38 -273175.56 -422428.60 -338610.35 -355974.10 -501422.75 -443477.87 -387298.70
2. the upper bound of the conformal CI is: 310100.958   88408.532   82866.221   62544.415  317490.705   10816.183 -133283.894   60696.978  -88945.409 -3963.312  -22437.681 -166537.758 -109267.215  -53844.108
3. the lower bound of the conformal CI is: -356823.8 -536025.1 -536025.1 -536025.1 -351281.4 -536025.1 -536025.1 -536025.1 -536025.1 -536025.1 -536025.1 -536025.1 -536025.1 -536025.1
It looks like that the lower bound is bounded by -536025.1.
I am wondering how to understand this result. 
I look forward to you reply. Thank you in advance!

**Comment by kwuthrich** [comment]
I think this may have to do with your choice of ci_grid. In the code, the lower bound is bounded below by the lower end point of the grid. So if the grid is not large enough, it may be that you always end up with the smallest value. Hope this helps.
